/** Secrets and optional bindings (not generated by wrangler types). */
declare namespace Cloudflare {
  interface Env {
    ELEVENLABS_API_KEY: string;
    JAM_BUCKET?: R2Bucket;
    CLOUDFLARE_AI_GATEWAY?: string;
  }
}
